// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBFX5m_MjxR8Ct5mJU-SL0I8_5FQRxuFIw',
    appId: '1:944620268143:web:6e31e066562ff6fcdbfb9a',
    messagingSenderId: '944620268143',
    projectId: 'appretargeting-b6139',
    authDomain: 'appretargeting-b6139.firebaseapp.com',
    storageBucket: 'appretargeting-b6139.firebasestorage.app',
    measurementId: 'G-0EGXZH7V8N',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC5_hbptV-daj10rQ6hvHyLqmioaqUP9Vo',
    appId: '1:944620268143:android:9a431ebb4ac81d9edbfb9a',
    messagingSenderId: '944620268143',
    projectId: 'appretargeting-b6139',
    storageBucket: 'appretargeting-b6139.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDiB9fw7wj5vtVNQhKdq_YAjtvMfMYzShE',
    appId: '1:944620268143:ios:697403b9594b5a9ddbfb9a',
    messagingSenderId: '944620268143',
    projectId: 'appretargeting-b6139',
    storageBucket: 'appretargeting-b6139.firebasestorage.app',
    iosBundleId: 'com.example.appretargeting',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDiB9fw7wj5vtVNQhKdq_YAjtvMfMYzShE',
    appId: '1:944620268143:ios:697403b9594b5a9ddbfb9a',
    messagingSenderId: '944620268143',
    projectId: 'appretargeting-b6139',
    storageBucket: 'appretargeting-b6139.firebasestorage.app',
    iosBundleId: 'com.example.appretargeting',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBFX5m_MjxR8Ct5mJU-SL0I8_5FQRxuFIw',
    appId: '1:944620268143:web:b7011bb5fe5e3fe8dbfb9a',
    messagingSenderId: '944620268143',
    projectId: 'appretargeting-b6139',
    authDomain: 'appretargeting-b6139.firebaseapp.com',
    storageBucket: 'appretargeting-b6139.firebasestorage.app',
    measurementId: 'G-KR967CLVTW',
  );

}